version: 1

project:
  name: "STAT 159 Homework 3 – LIGO Analysis"
  author: "Cyrus Choi and LIGO Scientific Collaboration (LSC)"
  copyright: "2025"
  github: "https://github.com/UCB-stat-159-f25/hw3-xschnq"
  open_in_binder: true

site:
  title: "STAT 159 HW03 – LIGO"
  logo: ""
  favicon: ""
  use_repository_button: true
  use_edit_page_button: false
  use_issues_button: false
  use_download_button: false
  baseurl: "/hw3-xschnq/"
  static_path: _build/html/_static

html:
  favicon: ""
  comments: false
  announcement: ""
  extra_navbar: ""
  use_sidenotes: true
  home_page_in_navbar: true
  search_bar_text: "Search"