name: ligo

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26
  - scipy=1.11
  - h5py=3.9
  - matplotlib=3.8
  - ipykernel=6.29
  - mystmd
  - pip
  - pip:
      - ./ligotools
